---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Release.Name | quote }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env: 
        - name: PGHERO_CONFIG_PATH
          value: {{ .Values.fullpath | quote }}
        volumeMounts:
        - name: {{ .Values.secretname | quote }}
          mountPath: {{ .Values.fullpath | quote }}
          readOnly: true
          subPath: {{ .Values.configfile | quote }}
      volumes:
      - name: {{ .Values.secretname | quote }}
        secret:
          secretName: {{ .Values.secretname | quote }}