# This a plain secret please encrypt it self 
apiVersion: v1
kind: Secret
metadata:
    name: pghero-secret
type: Opaque
stringData:
  pghero.yml: |-
    databases:
      main:
        url: postgres://<username>:<password>@<host>:<port>/<dbname>
        capture_query_stats: 
        capture_space_stats:
      instance1:
        url: postgres://<username>:<password>@<host>:<port>/<dbname>
        capture_query_stats: instance1
        capture_space_stats: instance1
      instance2:
        url: postgres://<username>:<password>@<host>:<port>/<dbname>
        capture_query_stats: instance2
        capture_space_stats: instance2

    stats_database_url: postgres://<username>:<password>@<host>:<port>/<dbname>

    long_running_query_sec: 3
    slow_query_ms: 2000
    slow_query_calls: 100
    total_connections_threshold: 1000
    explain: true
    explain_timeout_sec: 10